
%% Cleaning 
close all
clc
clear
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\alshahin\OneDrive - Advanced Micro Devices Inc\Alireza\Analysis\Clustering\marron_data03.csv
%
% Auto-generated by MATLAB on 24-Nov-2021 15:57:43

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Depth", "DT", "RHOB", "NPHI", "PEF", "SGR", "RT"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
wlog1= readtable("C:\Users\alshahin\OneDrive - Advanced Micro Devices Inc\Alireza\Analysis\Clustering\marron_data03.csv", opts);

%% Clear temporary variables
clear opts

%% assignment  
wlog2=table2array(wlog1);
nr=size(wlog2,1);
nc=size(wlog2,2);
DEPTH=wlog2(:,1);
DT=wlog2(:,2);
RHOB=wlog2(:,3);
NPHI=wlog2(:,4);
PEF=wlog2(:,5);
GR=wlog2(:,6);
RT=wlog2(:,7);

%% QC plotting 
fs=14;
lw=2;

figure(1)
subplot(1,6,1)
plot(GR,DEPTH,'.b','LineWidth',lw)
xlabel('(API)','FontSize',fs)
ylabel('Depth(m)','FontSize',fs)
title('GR','FontSize',fs)
grid MINOR
grid on
set(gca,'YDir','reverse','FontSize',fs)       
subplot(1,6,3)
plot(RHOB,DEPTH,'.b','LineWidth',lw)
xlabel('(gr/cc)','FontSize',fs)
title('RHOB','FontSize',fs)
grid MINOR
grid on
set(gca,'YDir','reverse','FontSize',fs)  
subplot(1,6,2)
plot(RT,DEPTH,'.b','LineWidth',lw)
xlabel('(Omh-m)','FontSize',fs)
title('RT','FontSize',fs)
grid MINOR
grid on
set(gca,'YDir','reverse','FontSize',fs)  
subplot(1,6,4)
plot(NPHI,DEPTH,'.b','LineWidth',lw)
xlabel('(v/v)','FontSize',fs)
title('NPHI','FontSize',fs)
grid MINOR
grid on
set(gca,'YDir','reverse','FontSize',fs)  
subplot(1,6,5)
plot(DT,DEPTH,'.b','LineWidth',lw)
xlabel('(msec/m)','FontSize',fs)
title('DT','FontSize',fs)
grid MINOR
grid on
set(gca,'YDir','reverse','FontSize',fs)  
subplot(1,6,6)
plot(PEF,DEPTH,'.b','LineWidth',lw)
xlabel('(U)','FontSize',fs)
title('PEF','FontSize',fs)
grid MINOR
grid on
set(gca,'YDir','reverse','FontSize',fs)  

%% Remove rows with null values 
nully=-100;

wlog3=zeros(size(wlog2));
for jr=1:nr
    if (DT(jr)<0 || DT(jr)>500|| ...
        NPHI(jr)<-10 || NPHI(jr)>100 ||...
        GR(jr)<0 || GR(jr)>200)
        wlog3(jr,2:nc)=nully;
        wlog3(jr,1)=wlog2(jr,1);
    else
       wlog3(jr,:)=wlog2(jr,:); 
    end
end

wlog=wlog2(1,:);
for jr=2:nr
    if wlog3(jr,2)~=nully
        wlog=[wlog;wlog2(jr,:)];
    end   
end

DEPTH=wlog(:,1);
DT=wlog(:,2);
RHOB=wlog(:,3);
NPHI=wlog(:,4);
PEF=wlog(:,5);
GR=wlog(:,6);
RT=wlog(:,7);

%% Plotting after removing null values        
figure(2)
subplot(1,6,1)
plot(GR,DEPTH,'.b','LineWidth',lw)
xlabel('(API)','FontSize',fs)
ylabel('Depth(m)','FontSize',fs)
title('GR','FontSize',fs)
grid MINOR
grid on
set(gca,'YDir','reverse','FontSize',fs)       
subplot(1,6,3)
plot(RHOB,DEPTH,'.b','LineWidth',lw)
xlabel('(gr/cc)','FontSize',fs)
title('RHOB','FontSize',fs)
grid MINOR
grid on
set(gca,'YDir','reverse','FontSize',fs)  
subplot(1,6,2)
plot(RT,DEPTH,'.b','LineWidth',lw)
xlabel('(Omh-m)','FontSize',fs)
title('RT','FontSize',fs)
grid MINOR
grid on
set(gca,'YDir','reverse','FontSize',fs)  
subplot(1,6,4)
plot(NPHI,DEPTH,'.b','LineWidth',lw)
xlabel('(v/v)','FontSize',fs)
title('NPHI','FontSize',fs)
grid MINOR
grid on
set(gca,'YDir','reverse','FontSize',fs)  
subplot(1,6,5)
plot(DT,DEPTH,'.b','LineWidth',lw)
xlabel('(msec/m)','FontSize',fs)
title('DT','FontSize',fs)
grid MINOR
grid on
set(gca,'YDir','reverse','FontSize',fs)  
subplot(1,6,6)
plot(PEF,DEPTH,'.b','LineWidth',lw)
xlabel('(U)','FontSize',fs)
title('PEF','FontSize',fs)
grid MINOR
grid on
set(gca,'YDir','reverse','FontSize',fs)  

        